version: "3.7"
services:
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    ports:
      - "5436:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - airflow_network
    logging:
      options:
        max-size: 10m
        max-file: "3"

  webserver:
    build: docker/airflow
    restart: always
    depends_on:
      - postgres
    env_file:
      - .env
    logging:
      options:
        max-size: 10m
        max-file: "3"
    volumes:
      - ./airflow_files/:/usr/local/airflow/
      - ./infra/scalingo/:/config/scalingo
      - ~/.ssh:/config/ssh_keys
    ports:
      - "8080:8080"
    networks:
      - airflow_network
    command: webserver
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3
networks:
  airflow_network:
    driver: bridge
